import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:gurukool_teacher/services/supabase.service.dart';

/// Auto-generated by Backend Integration Agent
class AuthService {
  static Future<AuthResponse> signIn({
    required String email,
    required String password,
  }) async {
    try {
      final response = await SupabaseService.client.auth.signInWithPassword(
        email: email,
        password: password,
      );
      return response;
    } on AuthException catch (e) {
      throw AuthException(e.message);
    }
  }

  static Future<void> signOut() async {
    await SupabaseService.client.auth.signOut();
  }

  static Future<User?> getCurrentUser() async {
    return SupabaseService.currentUser;
  }

  static Future<Session?> getCurrentSession() async {
    return SupabaseService.client.auth.currentSession;
  }
}
