import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:gurukool_teacher/services/supabase_service.dart';

/// Auto-generated by Backend Integration Agent
class TeacherSessionsRealtimeService {
  static RealtimeChannel? _channel;

  static void subscribe({
    required Function(Map<String, dynamic>) onInsert,
    required Function(Map<String, dynamic>) onUpdate,
    required Function(Map<String, dynamic>) onDelete,
  }) {
    _channel = SupabaseService.client
        .channel('teacher_sessions_changes')
        .onPostgresChanges(
          event: PostgresChangeEvent.insert,
          schema: 'public',
          table: 'teacher_sessions',
          callback: (payload) => onInsert(payload.newRecord),
        )
        .onPostgresChanges(
          event: PostgresChangeEvent.update,
          schema: 'public',
          table: 'teacher_sessions',
          callback: (payload) => onUpdate(payload.newRecord),
        )
        .onPostgresChanges(
          event: PostgresChangeEvent.delete,
          schema: 'public',
          table: 'teacher_sessions',
          callback: (payload) => onDelete(payload.oldRecord),
        )
        .subscribe();
  }

  static void unsubscribe() {
    _channel?.unsubscribe();
    _channel = null;
  }
}
