/**
 * Smart Timesheet Automation Service with GPS Verification
 * Handles automatic time tracking, GPS verification, and billing calculations
 */

import { logger } from './logging.service';
import { offlineStorageManager } from './offline-storage.service';
import { webSocketService } from './websocket.service';

export interface GPSCoordinates {
  latitude: number;
  longitude: number;
  accuracy: number;
  timestamp: number;
}

export interface LocationVerification {
  isValid: boolean;
  distance: number;
  accuracy: number;
  confidenceScore: number;
  errorMessage?: string;
}

export interface TimesheetEntry {
  id: string;
  sessionId: string;
  teacherId: string;
  studentId: string;
  parentId?: string;
  startTime: Date;
  endTime?: Date;
  actualDuration?: number; // in minutes
  breakDuration?: number; // in minutes
  location: {
    start: GPSCoordinates;
    end?: GPSCoordinates;
    verifications: LocationVerification[];
  };
  billing: {
    hourlyRate: number;
    totalAmount?: number;
    currency: string;
    rateType: 'fixed' | 'hourly' | 'session';
  };
  status: 'active' | 'completed' | 'paused' | 'cancelled' | 'disputed';
  notes?: string;
  autoGenerated: boolean;
  verificationLevel: 'none' | 'basic' | 'gps' | 'enhanced';
  metadata: {
    deviceInfo?: string;
    appVersion?: string;
    networkType?: string;
    batteryLevel?: number;
  };
  createdAt: Date;
  updatedAt: Date;
}

export interface GeofenceRule {
  id: string;
  center: GPSCoordinates;
  radius: number; // in meters
  name: string;
  type: 'home' | 'school' | 'library' | 'custom';
  isActive: boolean;
  tolerance: number; // additional tolerance in meters
}

export interface BillingRate {
  id: string;
  teacherId: string;
  studentId?: string; // if null, applies to all students for this teacher
  hourlyRate: number;
  currency: string;
  effectiveFrom: Date;
  effectiveTo?: Date;
  rateType: 'standard' | 'premium' | 'weekend' | 'holiday';
  subjectPremium?: number; // additional rate for specific subjects
}

export interface AutoTimerConfig {
  teacherId: string;
  enableAutoStart: boolean;
  enableAutoStop: boolean;
  locationVerificationRequired: boolean;
  geofenceIds: string[];
  minimumSessionDuration: number; // in minutes
  maximumSessionDuration: number; // in minutes
  breakDetectionEnabled: boolean;
  autoBreakThreshold: number; // minutes of inactivity to auto-detect break
  reminderIntervals: number[]; // minutes before session end to send reminders
}

export class TimesheetAutomationService {
  private static instance: TimesheetAutomationService;
  private activeTimers: Map<string, TimesheetEntry> = new Map();
  private geofenceRules: Map<string, GeofenceRule> = new Map();
  private billingRates: Map<string, BillingRate[]> = new Map();
  private autoConfigs: Map<string, AutoTimerConfig> = new Map();
  private locationWatcher: number | null = null;
  private lastKnownPosition: GPSCoordinates | null = null;
  private reminderTimers: Map<string, NodeJS.Timeout> = new Map();

  private config = {
    gpsAccuracyThreshold: 50, // meters
    locationUpdateInterval: 60000, // 1 minute
    maxLocationAge: 300000, // 5 minutes
    defaultGeofenceRadius: 100, // meters
    minSessionDuration: 15, // minutes
    maxSessionDuration: 480, // 8 hours
    breakDetectionThreshold: 10, // minutes of inactivity
    billingRoundingMethod: 'up' as 'up' | 'down' | 'nearest',
    billingRoundingInterval: 15, // round to nearest 15 minutes
  };

  private constructor() {
    this.initializeLocationTracking();
    this.loadStoredData();
  }

  public static getInstance(): TimesheetAutomationService {
    if (!TimesheetAutomationService.instance) {
      TimesheetAutomationService.instance = new TimesheetAutomationService();
    }
    return TimesheetAutomationService.instance;
  }

  /**
   * Start automatic time tracking for a session
   */
  public async startSession(sessionId: string, teacherId: string, studentId: string, options: {
    parentId?: string;
    expectedLocation?: GPSCoordinates;
    hourlyRate?: number;
    notes?: string;
    requireLocationVerification?: boolean;
  }): Promise<string> {
    try {
      // Check if session is already active
      if (this.activeTimers.has(sessionId)) {
        throw new Error('Session timer is already active');
      }

      // Get current location
      const currentLocation = await this.getCurrentLocation();
      if (!currentLocation && options.requireLocationVerification !== false) {
        throw new Error('Unable to obtain GPS location for session start');
      }

      // Verify location if required
      let locationVerification: LocationVerification = {
        isValid: true,
        distance: 0,
        accuracy: currentLocation?.accuracy || 0,
        confidenceScore: 1.0
      };

      if (currentLocation && options.expectedLocation) {
        locationVerification = await this.verifyLocation(currentLocation, options.expectedLocation);
        if (!locationVerification.isValid) {
          logger.warn('app', 'Location verification failed for session start', locationVerification);
        }
      }

      // Get billing rate
      const billingRate = await this.getBillingRate(teacherId, studentId);

      // Create timesheet entry
      const timesheetEntry: TimesheetEntry = {
        id: this.generateTimesheetId(),
        sessionId,
        teacherId,
        studentId,
        startTime: new Date(),
        location: {
          start: currentLocation!,
          verifications: [locationVerification]
        },
        billing: {
          hourlyRate: options.hourlyRate || billingRate.hourlyRate,
          currency: billingRate.currency,
          rateType: billingRate.rateType === 'standard' ? 'hourly' : billingRate.rateType as any
        },
        status: 'active',
        notes: options.notes,
        autoGenerated: true,
        verificationLevel: currentLocation ? 'gps' : 'basic',
        metadata: await this.getDeviceMetadata(),
        createdAt: new Date(),
        updatedAt: new Date()
      };
      
      if (options.parentId !== undefined) {
        timesheetEntry.parentId = options.parentId;
      }

      // Store active timer
      this.activeTimers.set(sessionId, timesheetEntry);

      // Save to offline storage
      await offlineStorageManager.store('timesheets', timesheetEntry, 'high');

      // Set up auto-stop and reminders
      const autoConfig = this.autoConfigs.get(teacherId);
      if (autoConfig) {
        this.setupSessionReminders(sessionId, autoConfig);
      }

      // Notify via WebSocket
      await webSocketService.sendRealtimeMessage({
        type: 'session_update',
        from: teacherId,
        to: options.parentId || studentId,
        priority: 'medium',
        data: {
          action: 'session_started',
          sessionId,
          timesheetId: timesheetEntry.id,
          startTime: timesheetEntry.startTime,
          location: currentLocation
        }
      });

      logger.info('app', 'Session timer started', { sessionId, timesheetId: timesheetEntry.id });
      return timesheetEntry.id;

    } catch (error) {
      logger.error('app', 'Failed to start session timer', error instanceof Error ? error : undefined);
      throw error;
    }
  }

  /**
   * Stop session timer and calculate billing
   */
  public async stopSession(sessionId: string, options: {
    endLocation?: GPSCoordinates;
    notes?: string;
    manualDurationOverride?: number; // in minutes
  } = {}): Promise<TimesheetEntry> {
    try {
      const activeTimer = this.activeTimers.get(sessionId);
      if (!activeTimer) {
        throw new Error('No active timer found for session');
      }

      // Get end location
      const endLocation = options.endLocation || await this.getCurrentLocation();

      // Verify end location if GPS is available
      let endLocationVerification: LocationVerification = {
        isValid: true,
        distance: 0,
        accuracy: endLocation?.accuracy || 0,
        confidenceScore: 1.0
      };

      if (endLocation && activeTimer.location.start) {
        endLocationVerification = await this.verifyEndLocation(
          activeTimer.location.start, 
          endLocation
        );
      }

      // Calculate session duration
      const endTime = new Date();
      const durationMs = endTime.getTime() - activeTimer.startTime.getTime();
      const actualDuration = options.manualDurationOverride || Math.round(durationMs / (1000 * 60));

      // Validate duration
      if (actualDuration < this.config.minSessionDuration) {
        logger.warn('app', `Session duration ${actualDuration} minutes is below minimum ${this.config.minSessionDuration} minutes`);
      }

      if (actualDuration > this.config.maxSessionDuration) {
        logger.warn('app', `Session duration ${actualDuration} minutes exceeds maximum ${this.config.maxSessionDuration} minutes`);
      }

      // Calculate billing
      const roundedDuration = this.roundBillingDuration(actualDuration);
      const totalAmount = this.calculateBillingAmount(roundedDuration, activeTimer.billing.hourlyRate);

      // Update timesheet entry
      const completedEntry: TimesheetEntry = {
        ...activeTimer,
        endTime,
        actualDuration,
        location: {
          ...activeTimer.location,
          ...(endLocation ? { end: endLocation } : {}),
          verifications: [...activeTimer.location.verifications, endLocationVerification]
        },
        billing: {
          ...activeTimer.billing,
          totalAmount
        },
        status: 'completed',
        notes: options.notes ? `${activeTimer.notes || ''}${activeTimer.notes ? '\n' : ''}${options.notes}` : activeTimer.notes,
        updatedAt: new Date()
      };

      // Remove from active timers
      this.activeTimers.delete(sessionId);

      // Clear reminders
      const reminderTimer = this.reminderTimers.get(sessionId);
      if (reminderTimer) {
        clearTimeout(reminderTimer);
        this.reminderTimers.delete(sessionId);
      }

      // Update in offline storage
      await offlineStorageManager.store('timesheets', completedEntry, 'high');

      // Notify via WebSocket
      await webSocketService.sendRealtimeMessage({
        type: 'session_update',
        from: activeTimer.teacherId,
        to: activeTimer.parentId || activeTimer.studentId,
        priority: 'medium',
        data: {
          action: 'session_completed',
          sessionId,
          timesheetId: completedEntry.id,
          duration: actualDuration,
          totalAmount,
          endTime: endTime,
          location: endLocation
        }
      });

      logger.info('app', 'Session timer stopped', { 
        sessionId, 
        duration: actualDuration, 
        totalAmount 
      });

      return completedEntry;

    } catch (error) {
      logger.error('app', 'Failed to stop session timer', error instanceof Error ? error : undefined);
      throw error;
    }
  }

  /**
   * Pause active session
   */
  public async pauseSession(sessionId: string): Promise<void> {
    try {
      const activeTimer = this.activeTimers.get(sessionId);
      if (!activeTimer) {
        throw new Error('No active timer found for session');
      }

      activeTimer.status = 'paused';
      activeTimer.updatedAt = new Date();

      // Update in storage
      await offlineStorageManager.store('timesheets', activeTimer, 'high');

      logger.info('app', 'Session timer paused', { sessionId });

    } catch (error) {
      logger.error('app', 'Failed to pause session timer', error instanceof Error ? error : undefined);
      throw error;
    }
  }

  /**
   * Resume paused session
   */
  public async resumeSession(sessionId: string): Promise<void> {
    try {
      const activeTimer = this.activeTimers.get(sessionId);
      if (!activeTimer) {
        throw new Error('No active timer found for session');
      }

      if (activeTimer.status !== 'paused') {
        throw new Error('Session is not in paused state');
      }

      activeTimer.status = 'active';
      activeTimer.updatedAt = new Date();

      // Update in storage
      await offlineStorageManager.store('timesheets', activeTimer, 'high');

      logger.info('app', 'Session timer resumed', { sessionId });

    } catch (error) {
      logger.error('app', 'Failed to resume session timer', error instanceof Error ? error : undefined);
      throw error;
    }
  }

  /**
   * Get current location with GPS
   */
  private async getCurrentLocation(): Promise<GPSCoordinates | null> {
    return new Promise((resolve) => {
      if (!navigator.geolocation) {
        logger.warn('app', 'Geolocation is not supported by this browser');
        resolve(null);
        return;
      }

      const options = {
        enableHighAccuracy: true,
        timeout: 10000,
        maximumAge: this.config.maxLocationAge
      };

      navigator.geolocation.getCurrentPosition(
        (position) => {
          const coordinates: GPSCoordinates = {
            latitude: position.coords.latitude,
            longitude: position.coords.longitude,
            accuracy: position.coords.accuracy,
            timestamp: position.timestamp
          };
          this.lastKnownPosition = coordinates;
          resolve(coordinates);
        },
        (error) => {
          const errorObj = error instanceof Error ? error : new Error(`Geolocation error: ${error.message || 'Unknown error'}`);
          logger.error('app', 'Failed to get current location', errorObj);
          resolve(this.lastKnownPosition); // Fallback to last known position
        },
        options
      );
    });
  }

  /**
   * Verify location against expected coordinates
   */
  private async verifyLocation(current: GPSCoordinates, expected: GPSCoordinates): Promise<LocationVerification> {
    try {
      const distance = this.calculateDistance(current, expected);
      const accuracyFactor = Math.max(current.accuracy, expected.accuracy) / this.config.gpsAccuracyThreshold;
      const allowedDistance = this.config.defaultGeofenceRadius * (1 + accuracyFactor * 0.5);

      const isValid = distance <= allowedDistance;
      const confidenceScore = isValid ? 
        Math.max(0.5, 1 - (distance / allowedDistance)) : 
        Math.max(0.1, 0.5 - (distance - allowedDistance) / allowedDistance);

      const verification: LocationVerification = {
        isValid,
        distance,
        accuracy: current.accuracy,
        confidenceScore
      };
      
      if (!isValid) {
        verification.errorMessage = `Location is ${Math.round(distance)}m away from expected location`;
      }
      
      return verification;

    } catch (error) {
      return {
        isValid: false,
        distance: 0,
        accuracy: current.accuracy,
        confidenceScore: 0.1,
        errorMessage: 'Failed to verify location'
      };
    }
  }

  /**
   * Verify end location for reasonable movement
   */
  private async verifyEndLocation(start: GPSCoordinates, end: GPSCoordinates): Promise<LocationVerification> {
    const distance = this.calculateDistance(start, end);
    const maxReasonableDistance = 10000; // 10km max reasonable movement

    const isValid = distance <= maxReasonableDistance;
    const confidenceScore = isValid ? 
      Math.max(0.8, 1 - (distance / maxReasonableDistance)) : 
      0.3;

    const verification: LocationVerification = {
      isValid,
      distance,
      accuracy: end.accuracy,
      confidenceScore
    };
    
    if (!isValid) {
      verification.errorMessage = `End location is ${Math.round(distance)}m from start location`;
    }
    
    return verification;
  }

  /**
   * Calculate distance between two GPS coordinates using Haversine formula
   */
  private calculateDistance(coord1: GPSCoordinates, coord2: GPSCoordinates): number {
    const R = 6371000; // Earth's radius in meters
    const φ1 = coord1.latitude * Math.PI / 180;
    const φ2 = coord2.latitude * Math.PI / 180;
    const Δφ = (coord2.latitude - coord1.latitude) * Math.PI / 180;
    const Δλ = (coord2.longitude - coord1.longitude) * Math.PI / 180;

    const a = Math.sin(Δφ/2) * Math.sin(Δφ/2) +
              Math.cos(φ1) * Math.cos(φ2) *
              Math.sin(Δλ/2) * Math.sin(Δλ/2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));

    return R * c;
  }

  /**
   * Get billing rate for teacher-student combination
   */
  private async getBillingRate(teacherId: string, studentId: string): Promise<BillingRate> {
    const teacherRates = this.billingRates.get(teacherId) || [];
    const now = new Date();

    // Look for student-specific rate first
    let rate = teacherRates.find(r => 
      r.studentId === studentId &&
      r.effectiveFrom <= now &&
      (!r.effectiveTo || r.effectiveTo > now)
    );

    // Fall back to general rate for teacher
    if (!rate) {
      rate = teacherRates.find(r => 
        !r.studentId &&
        r.effectiveFrom <= now &&
        (!r.effectiveTo || r.effectiveTo > now)
      );
    }

    // Default rate if none found
    if (!rate) {
      return {
        id: 'default',
        teacherId,
        hourlyRate: 25.00,
        currency: 'USD',
        effectiveFrom: now,
        rateType: 'standard'
      };
    }

    return rate;
  }

  /**
   * Round billing duration according to configuration
   */
  private roundBillingDuration(actualMinutes: number): number {
    const intervalMinutes = this.config.billingRoundingInterval;
    
    switch (this.config.billingRoundingMethod) {
      case 'up':
        return Math.ceil(actualMinutes / intervalMinutes) * intervalMinutes;
      case 'down':
        return Math.floor(actualMinutes / intervalMinutes) * intervalMinutes;
      case 'nearest':
      default:
        return Math.round(actualMinutes / intervalMinutes) * intervalMinutes;
    }
  }

  /**
   * Calculate billing amount
   */
  private calculateBillingAmount(durationMinutes: number, hourlyRate: number): number {
    return Math.round((durationMinutes / 60) * hourlyRate * 100) / 100; // Round to 2 decimal places
  }

  /**
   * Set up session reminders
   */
  private setupSessionReminders(sessionId: string, config: AutoTimerConfig): void {
    if (config.reminderIntervals.length === 0) return;

    const activeTimer = this.activeTimers.get(sessionId);
    if (!activeTimer) return;

    // Set reminder for first interval
    const firstInterval = Math.min(...config.reminderIntervals);
    const reminderTime = firstInterval * 60 * 1000; // Convert to milliseconds

    const reminderTimer = setTimeout(() => {
      this.sendSessionReminder(sessionId, firstInterval);
    }, reminderTime);

    this.reminderTimers.set(sessionId, reminderTimer);
  }

  /**
   * Send session reminder
   */
  private async sendSessionReminder(sessionId: string, minutesElapsed: number): Promise<void> {
    const activeTimer = this.activeTimers.get(sessionId);
    if (!activeTimer) return;

    try {
      await webSocketService.sendRealtimeMessage({
        type: 'notification',
        from: 'system',
        to: activeTimer.teacherId,
        priority: 'medium',
        data: {
          type: 'session_reminder',
          sessionId,
          message: `Session has been running for ${minutesElapsed} minutes`,
          minutesElapsed,
          estimatedAmount: this.calculateBillingAmount(minutesElapsed, activeTimer.billing.hourlyRate)
        }
      });

      logger.debug('app', 'Session reminder sent', { sessionId, minutesElapsed });

    } catch (error) {
      logger.error('app', 'Failed to send session reminder', error instanceof Error ? error : undefined);
    }
  }

  /**
   * Get device metadata
   */
  private async getDeviceMetadata(): Promise<any> {
    const metadata: any = {
      appVersion: process.env.NEXT_PUBLIC_APP_VERSION || '1.0.0',
      userAgent: typeof navigator !== 'undefined' ? navigator.userAgent : 'unknown'
    };

    // Get network information if available
    if (typeof navigator !== 'undefined' && 'connection' in navigator) {
      const connection = (navigator as any).connection;
      metadata.networkType = connection?.effectiveType || 'unknown';
    }

    // Get battery information if available
    if (typeof navigator !== 'undefined' && 'getBattery' in navigator) {
      try {
        const battery = await (navigator as any).getBattery();
        metadata.batteryLevel = Math.round(battery.level * 100);
      } catch (error) {
        // Battery API not available
      }
    }

    return metadata;
  }

  /**
   * Initialize location tracking
   */
  private initializeLocationTracking(): void {
    if (typeof navigator !== 'undefined' && navigator.geolocation) {
      // Set up periodic location updates for active sessions
      setInterval(() => {
        if (this.activeTimers.size > 0) {
          this.getCurrentLocation(); // Updates lastKnownPosition
        }
      }, this.config.locationUpdateInterval);
    }
  }

  /**
   * Load stored data
   */
  private async loadStoredData(): Promise<void> {
    try {
      // Load active timers from storage
      const activeTimesheets = await offlineStorageManager.getAll<TimesheetEntry>('timesheets', { 
        index: 'status', 
        value: 'active' 
      });

      activeTimesheets.forEach(entry => {
        this.activeTimers.set(entry.sessionId, entry);
      });

      logger.info('app', `Loaded ${activeTimesheets.length} active timers from storage`);

    } catch (error) {
      logger.error('app', 'Failed to load stored timesheet data', error instanceof Error ? error : undefined);
    }
  }

  /**
   * Generate unique timesheet ID
   */
  private generateTimesheetId(): string {
    return `ts_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  }

  /**
   * Get active sessions
   */
  public getActiveSessions(): Map<string, TimesheetEntry> {
    return new Map(this.activeTimers);
  }

  /**
   * Get session statistics
   */
  public getSessionStats(): {
    activeSessions: number;
    totalSessions: number;
    averageDuration: number;
    totalRevenue: number;
  } {
    // This would typically query the database for historical data
    return {
      activeSessions: this.activeTimers.size,
      totalSessions: 0, // TODO: Query from storage
      averageDuration: 0, // TODO: Calculate from historical data  
      totalRevenue: 0 // TODO: Calculate from historical data
    };
  }

  /**
   * Set auto-timer configuration
   */
  public setAutoTimerConfig(teacherId: string, config: AutoTimerConfig): void {
    this.autoConfigs.set(teacherId, config);
    logger.info('app', 'Auto-timer configuration updated', { teacherId });
  }

  /**
   * Add geofence rule
   */
  public addGeofenceRule(rule: GeofenceRule): void {
    this.geofenceRules.set(rule.id, rule);
    logger.info('app', 'Geofence rule added', { ruleId: rule.id, name: rule.name });
  }

  /**
   * Add billing rate
   */
  public addBillingRate(rate: BillingRate): void {
    const teacherRates = this.billingRates.get(rate.teacherId) || [];
    teacherRates.push(rate);
    this.billingRates.set(rate.teacherId, teacherRates);
    logger.info('app', 'Billing rate added', { teacherId: rate.teacherId, rate: rate.hourlyRate });
  }

  /**
   * Clean up resources
   */
  public cleanup(): void {
    // Clear location watcher
    if (this.locationWatcher !== null) {
      navigator.geolocation.clearWatch(this.locationWatcher);
      this.locationWatcher = null;
    }

    // Clear reminder timers
    this.reminderTimers.forEach(timer => clearTimeout(timer));
    this.reminderTimers.clear();

    // Clear active timers
    this.activeTimers.clear();

    logger.info('app', 'Timesheet automation service cleaned up');
  }
}

// Export singleton instance
export const timesheetAutomationService = TimesheetAutomationService.getInstance();