import 'package:json_annotation/json_annotation.dart';

part 'students.g.dart';

/// Auto-generated by Backend Integration Agent from Supabase table: students
/// DO NOT EDIT MANUALLY
@JsonSerializable()
class Students {
  final String id;
  final DateTime createdAt;
  final DateTime updatedAt;
  // TODO: Add fields based on schema

  Students({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
  });

  factory Students.fromJson(Map<String, dynamic> json) =>
      _$StudentsFromJson(json);

  Map<String, dynamic> toJson() => _$StudentsToJson(this);
}
