import 'package:json_annotation/json_annotation.dart';

part 'teacher_sessions.g.dart';

/// Auto-generated by Backend Integration Agent from Supabase table: teacher_sessions
/// DO NOT EDIT MANUALLY
@JsonSerializable()
class TeacherSessions {
  final String id;
  final DateTime createdAt;
  final DateTime updatedAt;
  // TODO: Add fields based on schema

  TeacherSessions({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
  });

  factory TeacherSessions.fromJson(Map<String, dynamic> json) =>
      _$TeacherSessionsFromJson(json);

  Map<String, dynamic> toJson() => _$TeacherSessionsToJson(this);
}
