import 'package:json_annotation/json_annotation.dart';

part 'teachers.g.dart';

/// Auto-generated by Backend Integration Agent from Supabase table: teachers
/// DO NOT EDIT MANUALLY
@JsonSerializable()
class Teachers {
  final String id;
  final DateTime createdAt;
  final DateTime updatedAt;
  // TODO: Add fields based on schema

  Teachers({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
  });

  factory Teachers.fromJson(Map<String, dynamic> json) =>
      _$TeachersFromJson(json);

  Map<String, dynamic> toJson() => _$TeachersToJson(this);
}
