import 'package:json_annotation/json_annotation.dart';

part 'teacher_qr_codes.g.dart';

/// Auto-generated by Backend Integration Agent from Supabase table: teacher_qr_codes
/// DO NOT EDIT MANUALLY
@JsonSerializable()
class TeacherQrCodes {
  final String id;
  final DateTime createdAt;
  final DateTime updatedAt;
  // TODO: Add fields based on schema

  TeacherQrCodes({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
  });

  factory TeacherQrCodes.fromJson(Map<String, dynamic> json) =>
      _$TeacherQrCodesFromJson(json);

  Map<String, dynamic> toJson() => _$TeacherQrCodesToJson(this);
}
