// Core User Types
export interface User {
  id: string;
  email: string;
  name: string;
  role: 'parent' | 'teacher' | 'admin';
  preferences: UserPreferences;
  createdAt: Date;
  lastActive: Date;
}

export interface UserPreferences {
  notifications: NotificationSettings;
  dashboard: DashboardConfig;
  privacy: PrivacySettings;
  accessibility: AccessibilitySettings;
}

export interface NotificationSettings {
  email: boolean;
  push: boolean;
  sms: boolean;
  inApp: boolean;
  frequency: 'immediate' | 'hourly' | 'daily';
}

export interface DashboardConfig {
  layout: 'compact' | 'detailed';
  theme: 'light' | 'dark' | 'auto';
  widgets: string[];
}

export interface PrivacySettings {
  dataSharing: boolean;
  analytics: boolean;
  aiTraining: boolean;
}

export interface AccessibilitySettings {
  fontSize: 'small' | 'medium' | 'large';
  highContrast: boolean;
  reducedMotion: boolean;
  screenReader: boolean;
}

// Session Management Types
export type SessionStatus =
  | 'scheduled'
  | 'in-progress'
  | 'completed'
  | 'cancelled'
  | 'rescheduled';

export interface Session {
  id: string;
  studentId?: string; // Optional for test compatibility
  teacherId?: string; // Optional for test compatibility
  parentId?: string; // Optional for test compatibility
  subject?: string; // Optional for test compatibility
  scheduledStart: Date;
  scheduledEnd?: Date;
  actualStart?: Date;
  actualEnd?: Date;
  location?: Location | string; // Allow string for backward compatibility
  status?: SessionStatus;
  notes?: string;
  aiInsights?: AIInsight[];
  attachments?: Attachment[];
  // AI-Enhanced Fields (making them optional for compatibility)
  aiRecommendations?: any[];
  learningPatterns?: any[];
  sessionAnalytics?: any;
  conflictResolution?: any;
  autoGeneratedNotes?: any;
  // Metadata (making them optional for compatibility)
  createdAt?: Date;
  updatedAt?: Date;
  version?: number;
}

export interface Location {
  address: string;
  coordinates: {
    latitude: number;
    longitude: number;
  };
  verified: boolean;
}

export interface Attachment {
  id: string;
  filename: string;
  url: string;
  type: string;
  size: number;
  uploadedAt: Date;
}

// AI and Analytics Types
export interface AIInsight {
  id: string;
  sessionId: string;
  type: 'progress' | 'recommendation' | 'alert' | 'prediction';
  content: string;
  confidence: number;
  metadata: Record<string, any>;
  createdAt: Date;
  // Extended properties for compatibility
  title?: string;
  description?: string;
  severity?: 'low' | 'medium' | 'high' | 'critical'; // Added 'critical'
  suggestedActions?: string[];
  category?: string;
  generatedAt?: Date;
  studentId?: string;
}

export interface LearningAnalytics {
  studentId: string;
  subject: string;
  progressMetrics: ProgressMetric[];
  learningPatterns: LearningPattern[];
  recommendations: Recommendation[];
  lastUpdated: Date;
}

export interface ProgressMetric {
  metric: string;
  value: number;
  trend: 'improving' | 'stable' | 'declining';
  period: string;
}

export interface LearningPattern {
  pattern: string;
  frequency: number;
  impact: 'positive' | 'neutral' | 'negative';
  confidence: number;
}

export interface Recommendation {
  id: string;
  type: 'action' | 'resource' | 'schedule';
  title: string;
  description: string;
  priority: 'high' | 'medium' | 'low';
  actionable: boolean;
}

// Authentication Types
export interface QRAuthState {
  qrCode: string;
  isScanning: boolean;
  authStatus: 'pending' | 'success' | 'expired' | 'error';
  user?: User;
}

export interface AuthToken {
  accessToken: string;
  refreshToken: string;
  expiresAt: Date;
}

// AI Agent Types
export interface AIAgent {
  id: string;
  name: string;
  capabilities: string[];
  priority: number;
  execute(context: AgentContext): Promise<AgentResult>;
}

export interface AgentContext {
  user: User | null;
  sessionData: Session[];
  preferences: UserPreferences;
  historicalData: HistoricalData;
  // Core context properties
  timestamp?: number;
  sessionId?: string;
  // Authentication context
  tokenData?: any;
  userAgent?: string;
  ipAddress?: string;
  multiFactorRequired?: boolean;
  riskScore?: number;
  authFactors?: any[];
  // Task automation context
  urgencyLevel?: 'low' | 'medium' | 'high' | 'critical';
  batchMode?: boolean;
  batchData?: any[];
  // Communication context
  notificationPreferences?: NotificationSettings;
  communicationChannel?: 'email' | 'sms' | 'push' | 'in-app';
  // Analytics context
  analyticsScope?: 'session' | 'student' | 'teacher' | 'global';
  timeRange?: { start: Date; end: Date };
  // System context
  healthCheck?: boolean;
  eventType?: string;
  eventData?: any;
  context?: string;
  deviceInfo?: string;
  mcpData?: any;
  // Additional metadata
  metadata?: Record<string, any>;
}

export interface AgentResult {
  success: boolean;
  data?: any;
  insights?: AIInsight[] | undefined;
  actions?: RecommendedAction[] | undefined;
  error?: string | undefined;
  // Performance metrics
  executionTime?: number | undefined;
  confidence?: number | undefined;
  // Follow-up actions
  nextActions?: string[] | undefined;
  // Metadata
  metadata?: Record<string, any> | undefined;
}

export interface RecommendedAction {
  id: string;
  type: string;
  description: string;
  priority: number;
  automated: boolean;
}

export interface HistoricalData {
  sessions: Session[];
  analytics: LearningAnalytics[];
  interactions: UserInteraction[];
}

export interface UserInteraction {
  id: string;
  userId: string;
  action: string;
  timestamp: Date;
  metadata: Record<string, any>;
}

// Sync and Offline Types
export interface OfflineAction {
  id: string;
  type: string;
  payload: any;
  timestamp: number;
  priority: 'high' | 'medium' | 'low';
  retryCount: number;
}

export interface SyncStatus {
  isOnline: boolean;
  lastSync: Date;
  pendingActions: number;
  conflictsCount: number;
}

// Error Types
export enum AuthErrorType {
  QR_EXPIRED = 'qr_expired',
  INVALID_TOKEN = 'invalid_token',
  INSUFFICIENT_PERMISSIONS = 'insufficient_permissions',
  RATE_LIMITED = 'rate_limited',
}

export enum AIErrorType {
  MODEL_UNAVAILABLE = 'model_unavailable',
  INSUFFICIENT_DATA = 'insufficient_data',
  PROCESSING_TIMEOUT = 'processing_timeout',
  CONFIDENCE_TOO_LOW = 'confidence_too_low',
}

// UI Component Types
export interface SmartFormProps {
  schema: any; // Zod schema
  onSubmit: (data: any) => Promise<void>;
  aiAssisted?: boolean;
  realTimeValidation?: boolean;
}

export interface AnalyticsDashboardProps {
  data: LearningAnalytics;
  chartType: 'line' | 'bar' | 'pie' | 'heatmap';
  interactive?: boolean;
  aiInsights?: boolean;
}

export interface GestureCardProps {
  children: React.ReactNode;
  swipeActions?: SwipeAction[];
  dragEnabled?: boolean;
  hapticFeedback?: boolean;
}

export interface SwipeAction {
  id: string;
  label: string;
  icon: string;
  color: string;
  action: () => void;
}

// Academic Standards and Syllabus Types
export type Country = 'UK' | 'US' | 'India';

export interface AcademicStandard {
  country: Country;
  name: string;
  description: string;
  gradeLevels: GradeLevel[];
  subjects: Subject[];
  assessmentMethods: string[];
  learningOutcomes: LearningOutcome[];
}

export interface GradeLevel {
  id: string;
  name: string;
  ageRange: string;
  description: string;
  subjects: Subject[];
  keySkills: string[];
  assessmentCriteria: string[];
}

export interface Subject {
  id: string;
  name: string;
  description: string;
  topics: Topic[];
  skills: string[];
  assessmentMethods: string[];
  resources: string[];
  countrySpecific?: {
    [key in Country]?: {
      name: string;
      topics: Topic[];
      assessmentMethods: string[];
    };
  };
}

export interface Topic {
  id: string;
  name: string;
  description: string;
  learningObjectives: string[];
  activities: string[];
  resources: string[];
  assessmentCriteria: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

export interface LearningOutcome {
  id: string;
  category: string;
  outcomes: string[];
  assessmentMethods: string[];
  gradeLevel: string;
}

// Homeschooling Options Types
export interface HomeschoolingOptions {
  socialization: SocializationOption[];
  physicalEducation: PhysicalEducationOption[];
  extracurricular: ExtracurricularOption[];
  communityInvolvement: CommunityInvolvementOption[];
}

export interface SocializationOption {
  id: string;
  name: string;
  description: string;
  frequency: 'daily' | 'weekly' | 'monthly' | 'quarterly';
  groupSize: 'small' | 'medium' | 'large';
  ageGroups: string[];
  activities: string[];
  benefits: string[];
  requirements: string[];
  cost: 'free' | 'low' | 'medium' | 'high';
  location: 'online' | 'local' | 'hybrid';
}

export interface PhysicalEducationOption {
  id: string;
  name: string;
  description: string;
  category:
    | 'sports'
    | 'fitness'
    | 'outdoor'
    | 'dance'
    | 'martial-arts'
    | 'swimming'
    | 'yoga'
    | 'other';
  frequency: 'daily' | 'weekly' | 'monthly';
  duration: string;
  ageGroups: string[];
  skills: string[];
  equipment: string[];
  benefits: string[];
  requirements: string[];
  cost: 'free' | 'low' | 'medium' | 'high';
  location: 'home' | 'local' | 'gym' | 'outdoor' | 'online';
}

export interface ExtracurricularOption {
  id: string;
  name: string;
  description: string;
  category:
    | 'arts'
    | 'music'
    | 'science'
    | 'technology'
    | 'language'
    | 'cooking'
    | 'gardening'
    | 'other';
  frequency: 'weekly' | 'monthly' | 'quarterly';
  ageGroups: string[];
  activities: string[];
  skills: string[];
  benefits: string[];
  requirements: string[];
  cost: 'free' | 'low' | 'medium' | 'high';
  location: 'home' | 'local' | 'online';
}

export interface CommunityInvolvementOption {
  id: string;
  name: string;
  description: string;
  category:
    | 'volunteering'
    | 'clubs'
    | 'religious'
    | 'cultural'
    | 'sports-teams'
    | 'scouting'
    | 'other';
  frequency: 'weekly' | 'monthly' | 'quarterly';
  ageGroups: string[];
  activities: string[];
  benefits: string[];
  requirements: string[];
  cost: 'free' | 'low' | 'medium' | 'high';
  location: 'local' | 'online';
}

// Enhanced Student Types
export interface Student {
  id: string;
  name: string;
  age: number;
  grade: string;
  country: Country;
  academicStandard: AcademicStandard;
  subjects: Subject[];
  homeschoolingOptions: HomeschoolingOptions;
  learningStyle?: string;
  specialNeeds?: string;
  interests?: string;
  teacher?: string;
  progress: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface TeacherProfile {
  id: string;
  userId?: string; // user_id from users table (for session matching)
  name: string;
  email: string;
  phone?: string;
  subjects: string[];
  experience: number; // years of experience
  qualifications: string[];
  specializations: string[];
  hourlyRate: number;
  availability: {
    days: string[];
    timeSlots: string[];
  };
  location: {
    address: string;
    coordinates?: {
      latitude: number;
      longitude: number;
    };
  };
  bio?: string;
  profilePictureUrl?: string;
  status?: 'available' | 'assigned' | 'unavailable';
  parentId: string; // parent who created this teacher
  createdAt: Date;
  updatedAt: Date;
}

export interface StudentProfile {
  id: string;
  name: string;
  age: number;
  grade: string;
  country: Country;
  academicStandard: AcademicStandard;
  selectedSubjects: Subject[];
  selectedSocialization: SocializationOption[];
  selectedPhysicalEducation: PhysicalEducationOption[];
  selectedExtracurricular: ExtracurricularOption[];
  selectedCommunityInvolvement: CommunityInvolvementOption[];
  // Data Sheet Activity Categories
  selectedSensoryActivities?: string[];
  selectedWritingActivities?: string[];
  selectedCommunicationActivities?: string[];
  selectedSocialActivities?: string[];
  selectedMotorActivities?: string[];
  selectedAcademicActivities?: string[];
  learningStyle?: string;
  specialNeeds?: string;
  interests?: string;
  parentId: string;
  assignedTeachers?: string[]; // Array of teacher IDs
  teacherNotes?: string; // Notes for teachers
  createdAt: Date;
  updatedAt: Date;
}

// Re-export types from session.types.ts for convenience
export type {
  AIRecommendation,
  SessionRecord,
  SessionQuery,
  SchedulingRequest,
  LearningPattern as SessionLearningPattern,
  SessionAnalytics,
  ConflictResolution,
  AutoGeneratedNotes,
  SchedulingResult,
  SchedulingConflict,
  AlternativeSchedule,
  SessionUpdateRequest,
  TimeSlot,
  SchedulingConstraint,
} from './session.types';

// ============================================================================
// Face Recognition Types (v2.0 - Server-Side Verification)
// ============================================================================

/**
 * Database record for encrypted student face data
 */
export interface StudentFaceRecord {
  id: string;
  student_id: string;
  face_descriptor_encrypted: Buffer; // AES-256-GCM encrypted data
  descriptor_version: string;
  quality_score: number;
  enrollment_metadata: FaceEnrollmentMetadata;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * Metadata captured during face enrollment
 */
export interface FaceEnrollmentMetadata {
  device?: string;
  browser?: string;
  lighting?: 'poor' | 'fair' | 'good' | 'excellent';
  angle?: 'frontal' | 'slight_left' | 'slight_right';
  capturedAt?: string;
}

/**
 * Result from client-side face detection (descriptor sent to server for matching)
 */
export interface FaceDetectionResult {
  descriptor: number[]; // 128 floats - sent to server for verification
  boundingBox: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
  qualityScore: number;
  landmarks: FaceLandmarks | null;
  // NO matchedStudent field - matching is done server-side only
}

/**
 * Face landmarks for quality assessment
 */
export interface FaceLandmarks {
  positions: Array<{ x: number; y: number }>;
  leftEye?: { x: number; y: number };
  rightEye?: { x: number; y: number };
  nose?: { x: number; y: number };
  mouth?: { x: number; y: number };
}

/**
 * Request payload for face enrollment
 */
export interface FaceEnrollRequest {
  studentId: string;
  descriptor: number[]; // 128-float array
  qualityScore: number;
  metadata?: FaceEnrollmentMetadata;
}

/**
 * Response from face enrollment API
 */
export interface FaceEnrollResponse {
  success: boolean;
  recordId?: string;
  message: string;
  error?: string;
}

/**
 * Request payload for server-side face verification
 * IMPORTANT: NO confidence field - server calculates this
 */
export interface FaceVerifyRequest {
  studentId: string;
  capturedDescriptor: number[]; // 128-float array
  // NO confidence field - server calculates this from distance
}

/**
 * Response from server-side face verification
 */
export interface FaceVerifyResponse {
  success: boolean;
  matched: boolean;
  confidence: number; // Server-calculated (0-1)
  distance: number; // Euclidean distance
  student?: {
    id: string;
    name: string;
    grade: string;
  };
  message: string;
  verifiedAt?: string;
  /**
   * Machine-readable error code for failure cases. Examples:
   *   - 'REENROLL_REQUIRED' — stored descriptor was generated with an
   *     incompatible model version; client should prompt re-enrollment.
   * Absent on success.
   */
  code?: string;
}

/**
 * Errors that can occur during face scanning
 */
export interface FaceScannerError {
  code: FaceScannerErrorCode;
  message: string;
  details?: string;
}

/**
 * Error codes for face scanner
 */
export type FaceScannerErrorCode =
  | 'CAMERA_DENIED'
  | 'CAMERA_NOT_FOUND'
  | 'NO_FACE'
  | 'MULTIPLE_FACES'
  | 'MODEL_LOAD_FAILED'
  | 'LOW_QUALITY'
  | 'SERVER_VERIFY_FAILED'
  | 'NETWORK_ERROR'
  | 'RATE_LIMITED'
  | 'ENCRYPTION_ERROR';

/**
 * Methods for verifying student identity at check-in
 */
export type VerificationMethod =
  | 'qr_code'
  | 'face_recognition'
  | 'biometric'
  | 'manual';

/**
 * Model loading progress state
 */
export interface ModelLoadingState {
  isLoading: boolean;
  progress: number; // 0-100
  currentModel?: string;
  error?: string;
}

/**
 * Face quality metrics for UI feedback
 */
export interface FaceQualityMetrics {
  overall: number; // 0-1
  lighting: 'poor' | 'fair' | 'good' | 'excellent';
  positioning: 'off_center' | 'too_close' | 'too_far' | 'good';
  angle: 'frontal' | 'slight_left' | 'slight_right' | 'profile';
  sharpness: number; // 0-1
}

/**
 * Assigned student with face enrollment status (for teacher view)
 * NOTE: Does NOT include face descriptors - those stay server-side
 */
export interface AssignedStudentWithFaceStatus {
  id: string;
  name: string;
  grade: string;
  hasFaceEnrolled: boolean; // true/false only - no descriptors
  hasActiveSession: boolean;
  lastCheckIn: string | undefined;
}

/**
 * Face verification audit log entry
 */
export interface FaceVerificationAuditEntry {
  id: string;
  teacher_id: string;
  student_id: string;
  verification_result:
    | 'success'
    | 'failed'
    | 'no_match'
    | 'rate_limited'
    | 'error';
  confidence_score: number;
  distance: number;
  device_info: Record<string, unknown>;
  ip_address: string;
  created_at: string;
}

/**
 * Face check-in request (after successful verification)
 */
export interface FaceCheckInRequest {
  studentId: string;
  action: 'check_in' | 'check_out';
  verificationConfidence: number; // Server-provided confidence from verify step
  notes?: string;
}

/**
 * Face check-in response
 */
export interface FaceCheckInResponse {
  success: boolean;
  sessionId?: string;
  action: 'check_in' | 'check_out';
  timestamp: string;
  message: string;
}
