// Core User Types
export interface User {
  id: string;
  email: string;
  name: string;
  role: 'parent' | 'teacher' | 'admin';
  preferences: UserPreferences;
  createdAt: Date;
  lastActive: Date;
}

export interface UserPreferences {
  notifications: NotificationSettings;
  dashboard: DashboardConfig;
  privacy: PrivacySettings;
  accessibility: AccessibilitySettings;
}

export interface NotificationSettings {
  email: boolean;
  push: boolean;
  sms: boolean;
  inApp: boolean;
  frequency: 'immediate' | 'hourly' | 'daily';
}

export interface DashboardConfig {
  layout: 'compact' | 'detailed';
  theme: 'light' | 'dark' | 'auto';
  widgets: string[];
}

export interface PrivacySettings {
  dataSharing: boolean;
  analytics: boolean;
  aiTraining: boolean;
}

export interface AccessibilitySettings {
  fontSize: 'small' | 'medium' | 'large';
  highContrast: boolean;
  reducedMotion: boolean;
  screenReader: boolean;
}

// Session Management Types
export type SessionStatus =
  | 'scheduled'
  | 'in-progress'
  | 'completed'
  | 'cancelled'
  | 'rescheduled';

export interface Session {
  id: string;
  studentId: string;
  teacherId: string;
  parentId: string;
  subject: string;
  scheduledStart: Date;
  scheduledEnd?: Date;
  actualStart?: Date;
  actualEnd?: Date;
  location?: Location;
  status?: SessionStatus;
  notes?: string;
  aiInsights?: AIInsight[];
  attachments?: Attachment[];
  // AI-Enhanced Fields (making them optional for compatibility)
  aiRecommendations?: any[];
  learningPatterns?: any[];
  sessionAnalytics?: any;
  conflictResolution?: any;
  autoGeneratedNotes?: any;
  // Metadata (making them optional for compatibility)
  createdAt?: Date;
  updatedAt?: Date;
  version?: number;
}

export interface Location {
  address: string;
  coordinates: {
    latitude: number;
    longitude: number;
  };
  verified: boolean;
}

export interface Attachment {
  id: string;
  filename: string;
  url: string;
  type: string;
  size: number;
  uploadedAt: Date;
}

// AI and Analytics Types
export interface AIInsight {
  id: string;
  sessionId: string;
  type: 'progress' | 'recommendation' | 'alert' | 'prediction';
  content: string;
  confidence: number;
  metadata: Record<string, any>;
  createdAt: Date;
}

export interface LearningAnalytics {
  studentId: string;
  subject: string;
  progressMetrics: ProgressMetric[];
  learningPatterns: LearningPattern[];
  recommendations: Recommendation[];
  lastUpdated: Date;
}

export interface ProgressMetric {
  metric: string;
  value: number;
  trend: 'improving' | 'stable' | 'declining';
  period: string;
}

export interface LearningPattern {
  pattern: string;
  frequency: number;
  impact: 'positive' | 'neutral' | 'negative';
  confidence: number;
}

export interface Recommendation {
  id: string;
  type: 'action' | 'resource' | 'schedule';
  title: string;
  description: string;
  priority: 'high' | 'medium' | 'low';
  actionable: boolean;
}

// Authentication Types
export interface QRAuthState {
  qrCode: string;
  isScanning: boolean;
  authStatus: 'pending' | 'success' | 'expired' | 'error';
  user?: User;
}

export interface AuthToken {
  accessToken: string;
  refreshToken: string;
  expiresAt: Date;
}

// AI Agent Types
export interface AIAgent {
  id: string;
  name: string;
  capabilities: string[];
  priority: number;
  execute(context: AgentContext): Promise<AgentResult>;
}

export interface AgentContext {
  user: User | null;
  sessionData: Session[];
  preferences: UserPreferences;
  historicalData: HistoricalData;
  // Core context properties
  timestamp?: number;
  sessionId?: string;
  // Authentication context
  tokenData?: any;
  userAgent?: string;
  ipAddress?: string;
  multiFactorRequired?: boolean;
  riskScore?: number;
  authFactors?: any[];
  // Task automation context
  urgencyLevel?: 'low' | 'medium' | 'high' | 'critical';
  batchMode?: boolean;
  batchData?: any[];
  // Communication context
  notificationPreferences?: NotificationSettings;
  communicationChannel?: 'email' | 'sms' | 'push' | 'in-app';
  // Analytics context
  analyticsScope?: 'session' | 'student' | 'teacher' | 'global';
  timeRange?: { start: Date; end: Date };
  // System context
  healthCheck?: boolean;
  eventType?: string;
  eventData?: any;
  context?: string;
  deviceInfo?: string;
  mcpData?: any;
  // Additional metadata
  metadata?: Record<string, any>;
}

export interface AgentResult {
  success: boolean;
  data?: any;
  insights?: AIInsight[];
  actions?: RecommendedAction[];
  error?: string;
  // Performance metrics
  executionTime?: number;
  confidence?: number;
  // Follow-up actions
  nextActions?: string[];
  // Metadata
  metadata?: Record<string, any>;
}

export interface RecommendedAction {
  id: string;
  type: string;
  description: string;
  priority: number;
  automated: boolean;
}

export interface HistoricalData {
  sessions: Session[];
  analytics: LearningAnalytics[];
  interactions: UserInteraction[];
}

export interface UserInteraction {
  id: string;
  userId: string;
  action: string;
  timestamp: Date;
  metadata: Record<string, any>;
}

// Sync and Offline Types
export interface OfflineAction {
  id: string;
  type: string;
  payload: any;
  timestamp: number;
  priority: 'high' | 'medium' | 'low';
  retryCount: number;
}

export interface SyncStatus {
  isOnline: boolean;
  lastSync: Date;
  pendingActions: number;
  conflictsCount: number;
}

// Error Types
export enum AuthErrorType {
  QR_EXPIRED = 'qr_expired',
  INVALID_TOKEN = 'invalid_token',
  INSUFFICIENT_PERMISSIONS = 'insufficient_permissions',
  RATE_LIMITED = 'rate_limited',
}

export enum AIErrorType {
  MODEL_UNAVAILABLE = 'model_unavailable',
  INSUFFICIENT_DATA = 'insufficient_data',
  PROCESSING_TIMEOUT = 'processing_timeout',
  CONFIDENCE_TOO_LOW = 'confidence_too_low',
}

// UI Component Types
export interface SmartFormProps {
  schema: any; // Zod schema
  onSubmit: (data: any) => Promise<void>;
  aiAssisted?: boolean;
  realTimeValidation?: boolean;
}

export interface AnalyticsDashboardProps {
  data: LearningAnalytics;
  chartType: 'line' | 'bar' | 'pie' | 'heatmap';
  interactive?: boolean;
  aiInsights?: boolean;
}

export interface GestureCardProps {
  children: React.ReactNode;
  swipeActions?: SwipeAction[];
  dragEnabled?: boolean;
  hapticFeedback?: boolean;
}

export interface SwipeAction {
  id: string;
  label: string;
  icon: string;
  color: string;
  action: () => void;
}

// Academic Standards and Syllabus Types
export type Country = 'UK' | 'US' | 'India';

export interface AcademicStandard {
  country: Country;
  name: string;
  description: string;
  gradeLevels: GradeLevel[];
  subjects: Subject[];
  assessmentMethods: string[];
  learningOutcomes: LearningOutcome[];
}

export interface GradeLevel {
  id: string;
  name: string;
  ageRange: string;
  description: string;
  subjects: Subject[];
  keySkills: string[];
  assessmentCriteria: string[];
}

export interface Subject {
  id: string;
  name: string;
  description: string;
  topics: Topic[];
  skills: string[];
  assessmentMethods: string[];
  resources: string[];
  countrySpecific?: {
    [key in Country]?: {
      name: string;
      topics: Topic[];
      assessmentMethods: string[];
    };
  };
}

export interface Topic {
  id: string;
  name: string;
  description: string;
  learningObjectives: string[];
  activities: string[];
  resources: string[];
  assessmentCriteria: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

export interface LearningOutcome {
  id: string;
  category: string;
  outcomes: string[];
  assessmentMethods: string[];
  gradeLevel: string;
}

// Homeschooling Options Types
export interface HomeschoolingOptions {
  socialization: SocializationOption[];
  physicalEducation: PhysicalEducationOption[];
  extracurricular: ExtracurricularOption[];
  communityInvolvement: CommunityInvolvementOption[];
}

export interface SocializationOption {
  id: string;
  name: string;
  description: string;
  frequency: 'daily' | 'weekly' | 'monthly' | 'quarterly';
  groupSize: 'small' | 'medium' | 'large';
  ageGroups: string[];
  activities: string[];
  benefits: string[];
  requirements: string[];
  cost: 'free' | 'low' | 'medium' | 'high';
  location: 'online' | 'local' | 'hybrid';
}

export interface PhysicalEducationOption {
  id: string;
  name: string;
  description: string;
  category:
    | 'sports'
    | 'fitness'
    | 'outdoor'
    | 'dance'
    | 'martial-arts'
    | 'swimming'
    | 'yoga'
    | 'other';
  frequency: 'daily' | 'weekly' | 'monthly';
  duration: string;
  ageGroups: string[];
  skills: string[];
  equipment: string[];
  benefits: string[];
  requirements: string[];
  cost: 'free' | 'low' | 'medium' | 'high';
  location: 'home' | 'local' | 'gym' | 'outdoor' | 'online';
}

export interface ExtracurricularOption {
  id: string;
  name: string;
  description: string;
  category:
    | 'arts'
    | 'music'
    | 'science'
    | 'technology'
    | 'language'
    | 'cooking'
    | 'gardening'
    | 'other';
  frequency: 'weekly' | 'monthly' | 'quarterly';
  ageGroups: string[];
  activities: string[];
  skills: string[];
  benefits: string[];
  requirements: string[];
  cost: 'free' | 'low' | 'medium' | 'high';
  location: 'home' | 'local' | 'online';
}

export interface CommunityInvolvementOption {
  id: string;
  name: string;
  description: string;
  category:
    | 'volunteering'
    | 'clubs'
    | 'religious'
    | 'cultural'
    | 'sports-teams'
    | 'scouting'
    | 'other';
  frequency: 'weekly' | 'monthly' | 'quarterly';
  ageGroups: string[];
  activities: string[];
  benefits: string[];
  requirements: string[];
  cost: 'free' | 'low' | 'medium' | 'high';
  location: 'local' | 'online';
}

// Enhanced Student Types
export interface Student {
  id: string;
  name: string;
  age: number;
  grade: string;
  country: Country;
  academicStandard: AcademicStandard;
  subjects: Subject[];
  homeschoolingOptions: HomeschoolingOptions;
  learningStyle?: string;
  specialNeeds?: string;
  interests?: string;
  teacher?: string;
  progress: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface StudentProfile {
  id: string;
  name: string;
  age: number;
  grade: string;
  country: Country;
  academicStandard: AcademicStandard;
  selectedSubjects: Subject[];
  selectedSocialization: SocializationOption[];
  selectedPhysicalEducation: PhysicalEducationOption[];
  selectedExtracurricular: ExtracurricularOption[];
  selectedCommunityInvolvement: CommunityInvolvementOption[];
  // Data Sheet Activity Categories
  selectedSensoryActivities?: string[];
  selectedWritingActivities?: string[];
  selectedCommunicationActivities?: string[];
  selectedSocialActivities?: string[];
  selectedMotorActivities?: string[];
  selectedAcademicActivities?: string[];
  learningStyle?: string;
  specialNeeds?: string;
  interests?: string;
  parentId: string;
  createdAt: Date;
  updatedAt: Date;
}
