// Enhanced Session Types with AI Integration
import { AIInsight, Location, Attachment, User } from './index';

export type SessionStatus = 'scheduled' | 'in-progress' | 'completed' | 'cancelled' | 'rescheduled';

export interface SessionRecord {
  id: string;
  studentId: string;
  teacherId: string;
  parentId: string;
  subject: string;
  scheduledStart: Date;
  scheduledEnd: Date;
  actualStart?: Date;
  actualEnd?: Date;
  location: Location;
  status: SessionStatus;
  notes?: string;
  attachments: Attachment[];
  
  // AI-Enhanced Fields
  aiInsights: AIInsight[];
  aiRecommendations: AIRecommendation[];
  learningPatterns: LearningPattern[];
  sessionAnalytics: SessionAnalytics;
  conflictResolution?: ConflictResolution;
  autoGeneratedNotes?: AutoGeneratedNotes;
  
  // Metadata
  createdAt: Date;
  updatedAt: Date;
  version: number;
}

export interface AIRecommendation {
  id: string;
  type: 'scheduling' | 'content' | 'approach' | 'resource';
  title: string;
  description: string;
  confidence: number;
  priority: 'high' | 'medium' | 'low';
  actionable: boolean;
  metadata: Record<string, any>;
  createdAt: Date;
  expiresAt?: Date;
}

export interface LearningPattern {
  id: string;
  pattern: string;
  frequency: number;
  impact: 'positive' | 'neutral' | 'negative';
  confidence: number;
  detectedAt: Date;
  metadata: Record<string, any>;
}

export interface SessionAnalytics {
  engagementScore: number;
  progressScore: number;
  difficultyLevel: number;
  conceptsMastered: string[];
  conceptsStruggling: string[];
  timeDistribution: TimeDistribution;
  interactionMetrics: InteractionMetrics;
  learningVelocity: number;
}

export interface TimeDistribution {
  instruction: number;
  practice: number;
  assessment: number;
  discussion: number;
  breaks: number;
}

export interface InteractionMetrics {
  questionsAsked: number;
  questionsAnswered: number;
  correctAnswers: number;
  incorrectAnswers: number;
  helpRequests: number;
  selfCorrections: number;
}

export interface ConflictResolution {
  conflictType: 'scheduling' | 'location' | 'resource' | 'preference';
  originalRequest: any;
  suggestedSolutions: ConflictSolution[];
  selectedSolution?: ConflictSolution;
  resolvedAt?: Date;
  resolvedBy?: string;
}

export interface ConflictSolution {
  id: string;
  description: string;
  impact: 'minimal' | 'moderate' | 'significant';
  confidence: number;
  metadata: Record<string, any>;
}

export interface AutoGeneratedNotes {
  summary: string;
  keyPoints: string[];
  achievements: string[];
  challenges: string[];
  nextSteps: string[];
  confidence: number;
  generatedAt: Date;
  reviewedBy?: string;
  approved: boolean;
}

export interface SchedulingRequest {
  studentId: string;
  teacherId: string;
  subject: string;
  preferredTimes: TimeSlot[];
  duration: number;
  location?: Location;
  priority: 'high' | 'medium' | 'low';
  constraints?: SchedulingConstraint[];
  metadata?: Record<string, any>;
}

export interface TimeSlot {
  start: Date;
  end: Date;
  flexibility: number; // 0-1, how flexible this time slot is
}

export interface SchedulingConstraint {
  type: 'location' | 'teacher' | 'student' | 'resource' | 'custom';
  description: string;
  weight: number; // 0-1, importance of this constraint
  metadata?: Record<string, any>;
}

export interface SchedulingResult {
  success: boolean;
  scheduledSession?: SessionRecord;
  conflicts?: SchedulingConflict[];
  alternatives?: AlternativeSchedule[];
  aiRecommendations?: AIRecommendation[];
}

export interface SchedulingConflict {
  type: 'time' | 'location' | 'teacher' | 'student' | 'resource';
  description: string;
  severity: 'low' | 'medium' | 'high';
  affectedSessions: string[];
  suggestedResolutions: ConflictSolution[];
}

export interface AlternativeSchedule {
  timeSlot: TimeSlot;
  confidence: number;
  tradeoffs: string[];
  benefits: string[];
}

export interface SessionUpdateRequest {
  sessionId: string;
  updates: Partial<SessionRecord>;
  reason?: string;
  requestedBy: string;
  aiAssisted?: boolean;
}

export interface SessionQuery {
  studentId?: string;
  teacherId?: string;
  parentId?: string;
  subject?: string;
  status?: SessionStatus[];
  dateRange?: {
    start: Date;
    end: Date;
  };
  location?: string;
  includeAIInsights?: boolean;
  includeAnalytics?: boolean;
  sortBy?: 'date' | 'subject' | 'status' | 'engagement';
  sortOrder?: 'asc' | 'desc';
  limit?: number;
  offset?: number;
}