// Auto-generated by Backend Integration Agent from Supabase table: teacher_sessions
// DO NOT EDIT MANUALLY

export interface TeacherSessions {
  id: string;
  created_at: string;
  updated_at: string;
  // TODO: Add fields based on schema
}
