// Auto-generated by Backend Integration Agent from Supabase table: teacher_qr_codes
// DO NOT EDIT MANUALLY

export interface TeacherQrCodes {
  id: string;
  created_at: string;
  updated_at: string;
  // TODO: Add fields based on schema
}
