'use client';

import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import {
  timesheetAutomationService,
  TimesheetEntry,
} from '@/services/timesheet-automation.service';

interface TimesheetManagerProps {
  teacherId: string;
  onClose?: () => void;
}

export const TimesheetManager: React.FC<TimesheetManagerProps> = ({
  teacherId,
  onClose,
}) => {
  const [timesheets, setTimesheets] = useState<TimesheetEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<'current' | 'history' | 'reports'>(
    'current'
  );
  const [selectedDate, setSelectedDate] = useState(
    new Date().toISOString().split('T')[0]
  );

  useEffect(() => {
    loadTimesheets();
  }, [teacherId, selectedDate]);

  const loadTimesheets = async () => {
    setLoading(true);
    try {
      // Mock data for demonstration
      const mockTimesheets: TimesheetEntry[] = [
        {
          id: '1',
          sessionId: 'session-1',
          teacherId: teacherId,
          studentId: 'student-1',
          parentId: 'parent-1',
          startTime: new Date('2024-12-17T09:00:00'),
          endTime: new Date('2024-12-17T11:00:00'),
          actualDuration: 120,
          breakDuration: 10,
          location: {
            start: { latitude: 51.5074, longitude: -0.1278 },
            end: { latitude: 51.5074, longitude: -0.1278 },
            verifications: [],
          },
          billing: {
            hourlyRate: 25,
            totalAmount: 50,
            currency: 'USD',
            rateType: 'hourly',
          },
          status: 'completed',
          notes: 'Mathematics session with Emma Johnson',
          autoGenerated: true,
          verificationLevel: 'gps',
          metadata: {},
          createdAt: new Date('2024-12-17T09:00:00'),
          updatedAt: new Date('2024-12-17T11:00:00'),
        },
        {
          id: '2',
          sessionId: 'session-2',
          teacherId: teacherId,
          studentId: 'student-2',
          parentId: 'parent-2',
          startTime: new Date('2024-12-17T14:00:00'),
          endTime: new Date('2024-12-17T15:30:00'),
          actualDuration: 90,
          breakDuration: 5,
          location: {
            start: { latitude: 51.5074, longitude: -0.1278 },
            end: { latitude: 51.5074, longitude: -0.1278 },
            verifications: [],
          },
          billing: {
            hourlyRate: 25,
            totalAmount: 37.5,
            currency: 'USD',
            rateType: 'hourly',
          },
          status: 'completed',
          notes: 'Science session with Alex Chen',
          autoGenerated: true,
          verificationLevel: 'gps',
          metadata: {},
          createdAt: new Date('2024-12-17T14:00:00'),
          updatedAt: new Date('2024-12-17T15:30:00'),
        },
      ];

      setTimesheets(mockTimesheets);
    } catch (error) {
      console.error('Error loading timesheets:', error);
    } finally {
      setLoading(false);
    }
  };

  const getStatusColor = (status: string) => {
    const colors = {
      active: 'bg-green-100 text-green-800',
      completed: 'bg-blue-100 text-blue-800',
      paused: 'bg-yellow-100 text-yellow-800',
      cancelled: 'bg-red-100 text-red-800',
      disputed: 'bg-orange-100 text-orange-800',
    };
    return colors[status as keyof typeof colors] || 'bg-gray-100 text-gray-800';
  };

  const formatDuration = (minutes: number) => {
    const hours = Math.floor(minutes / 60);
    const mins = minutes % 60;
    return `${hours}h ${mins}m`;
  };

  const calculateTotalHours = () => {
    return timesheets.reduce((total, timesheet) => {
      return total + (timesheet.actualDuration || 0);
    }, 0);
  };

  const calculateTotalEarnings = () => {
    return timesheets.reduce((total, timesheet) => {
      return total + (timesheet.billing.totalAmount || 0);
    }, 0);
  };

  if (loading) {
    return (
      <div className="bg-white rounded-lg shadow-sm border p-6">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
        <p className="mt-2 text-gray-600 text-center">Loading timesheets...</p>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-lg shadow-sm border">
      {/* Header */}
      <div className="px-6 py-4 border-b border-gray-200">
        <div className="flex justify-between items-center">
          <div>
            <h2 className="text-xl font-bold text-gray-900">
              Timesheet Management
            </h2>
            <p className="text-gray-600 mt-1">
              Track your teaching sessions and earnings
            </p>
          </div>
          {onClose && (
            <button
              onClick={onClose}
              className="text-gray-400 hover:text-gray-600"
            >
              <svg
                className="w-6 h-6"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          )}
        </div>
      </div>

      {/* Stats */}
      <div className="px-6 py-4 bg-gray-50 border-b border-gray-200">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="text-center">
            <p className="text-sm text-gray-600">Total Hours</p>
            <p className="text-2xl font-bold text-blue-600">
              {formatDuration(calculateTotalHours())}
            </p>
          </div>
          <div className="text-center">
            <p className="text-sm text-gray-600">Total Earnings</p>
            <p className="text-2xl font-bold text-green-600">
              ${calculateTotalEarnings().toFixed(2)}
            </p>
          </div>
          <div className="text-center">
            <p className="text-sm text-gray-600">Sessions</p>
            <p className="text-2xl font-bold text-purple-600">
              {timesheets.length}
            </p>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="px-6 py-4 border-b border-gray-200">
        <div className="flex space-x-4">
          {[
            { id: 'current', label: 'Current Sessions' },
            { id: 'history', label: 'History' },
            { id: 'reports', label: 'Reports' },
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`pb-2 px-1 border-b-2 font-medium text-sm ${
                activeTab === tab.id
                  ? 'border-blue-500 text-blue-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      {/* Content */}
      <div className="p-6">
        {activeTab === 'current' && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-4"
          >
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold text-gray-900">
                Current Sessions
              </h3>
              <button className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors">
                Start New Session
              </button>
            </div>

            {timesheets.filter(t => t.status === 'active').length === 0 ? (
              <div className="text-center py-8">
                <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <svg
                    className="w-8 h-8 text-gray-400"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                  </svg>
                </div>
                <p className="text-gray-600">No active sessions</p>
              </div>
            ) : (
              timesheets
                .filter(t => t.status === 'active')
                .map(timesheet => (
                  <div
                    key={timesheet.id}
                    className="border border-gray-200 rounded-lg p-4"
                  >
                    <div className="flex justify-between items-start">
                      <div>
                        <h4 className="font-medium text-gray-900">
                          Session {timesheet.sessionId}
                        </h4>
                        <p className="text-sm text-gray-600">
                          Started: {timesheet.startTime.toLocaleTimeString()}
                        </p>
                        <p className="text-sm text-gray-600">
                          Duration:{' '}
                          {formatDuration(timesheet.actualDuration || 0)}
                        </p>
                      </div>
                      <div className="text-right">
                        <span
                          className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusColor(timesheet.status)}`}
                        >
                          {timesheet.status}
                        </span>
                        <p className="text-sm font-medium text-gray-900 mt-1">
                          ${timesheet.billing.totalAmount?.toFixed(2)}
                        </p>
                      </div>
                    </div>
                    {timesheet.notes && (
                      <p className="text-sm text-gray-600 mt-2">
                        {timesheet.notes}
                      </p>
                    )}
                  </div>
                ))
            )}
          </motion.div>
        )}

        {activeTab === 'history' && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-4"
          >
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold text-gray-900">
                Session History
              </h3>
              <input
                type="date"
                value={selectedDate}
                onChange={e => setSelectedDate(e.target.value)}
                className="border border-gray-300 rounded-lg px-3 py-2"
              />
            </div>

            {timesheets.length === 0 ? (
              <div className="text-center py-8">
                <p className="text-gray-600">No sessions found</p>
              </div>
            ) : (
              <div className="space-y-4">
                {timesheets.map(timesheet => (
                  <div
                    key={timesheet.id}
                    className="border border-gray-200 rounded-lg p-4"
                  >
                    <div className="flex justify-between items-start">
                      <div>
                        <h4 className="font-medium text-gray-900">
                          Session {timesheet.sessionId}
                        </h4>
                        <p className="text-sm text-gray-600">
                          {timesheet.startTime.toLocaleDateString()}{' '}
                          {timesheet.startTime.toLocaleTimeString()} -{' '}
                          {timesheet.endTime?.toLocaleTimeString()}
                        </p>
                        <p className="text-sm text-gray-600">
                          Duration:{' '}
                          {formatDuration(timesheet.actualDuration || 0)}
                        </p>
                        {timesheet.notes && (
                          <p className="text-sm text-gray-600 mt-1">
                            {timesheet.notes}
                          </p>
                        )}
                      </div>
                      <div className="text-right">
                        <span
                          className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusColor(timesheet.status)}`}
                        >
                          {timesheet.status}
                        </span>
                        <p className="text-sm font-medium text-gray-900 mt-1">
                          ${timesheet.billing.totalAmount?.toFixed(2)}
                        </p>
                        <p className="text-xs text-gray-500">
                          ${timesheet.billing.hourlyRate}/hour
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </motion.div>
        )}

        {activeTab === 'reports' && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-6"
          >
            <h3 className="text-lg font-semibold text-gray-900">
              Timesheet Reports
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-gray-50 rounded-lg p-6">
                <h4 className="font-medium text-gray-900 mb-4">
                  Weekly Summary
                </h4>
                <div className="space-y-3">
                  <div className="flex justify-between">
                    <span className="text-gray-600">Total Hours:</span>
                    <span className="font-medium">
                      {formatDuration(calculateTotalHours())}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Total Earnings:</span>
                    <span className="font-medium">
                      ${calculateTotalEarnings().toFixed(2)}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Average Rate:</span>
                    <span className="font-medium">
                      $
                      {(
                        calculateTotalEarnings() /
                        (calculateTotalHours() / 60)
                      ).toFixed(2)}
                      /hour
                    </span>
                  </div>
                </div>
              </div>

              <div className="bg-gray-50 rounded-lg p-6">
                <h4 className="font-medium text-gray-900 mb-4">
                  Quick Actions
                </h4>
                <div className="space-y-3">
                  <button className="w-full bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors">
                    Export Timesheet
                  </button>
                  <button className="w-full bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition-colors">
                    Generate Invoice
                  </button>
                  <button className="w-full bg-purple-600 text-white px-4 py-2 rounded-lg hover:bg-purple-700 transition-colors">
                    View Analytics
                  </button>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </div>
    </div>
  );
};
